name: spectrofy
dependencies:
  - jupyter
  - pandas
  - matplotlib
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cpuonly
  - pip
  - pip:
      - spotipy
      - librosa
      - streamlit
      - neptune
